import { Router } from 'express';
import { requireAuth } from '../middleware/auth.js';
import { list, getById, create, update, receber, remove } from '../controllers/contaReceber.controller.js';
const router = Router();
router.use(requireAuth);
router.get('/', list);
router.get('/:id', getById);
router.post('/', create);
router.put('/:id', update);
router.post('/:id/receber', receber);
router.delete('/:id', remove);
export default router;
