import { Router } from 'express';
import { requireAuth } from '../middleware/auth.js';
import { list, getById, create, update, finalizar, cancelar, remove } from '../controllers/venda.controller.js';
const router = Router();
router.use(requireAuth);
router.get('/', list);
router.get('/:id', getById);
router.post('/', create);
router.put('/:id', update);
router.post('/:id/finalizar', finalizar);
router.post('/:id/cancelar', cancelar);
router.delete('/:id', remove);
router.get("/vendas/ultimas", ultimasVendas);
export default router;
